# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Thème Quire pour ECRiDiL 2018"
license = "MIT"
licenselink = "https://github.com/livrenum/theme-ecridil-2018/blob/master/LICENSE.md"
description = ""
homepage = "http://livrenum.ex-situ.info/"
tags = []
features = []
min_version = "0.50"

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
